// NEXIS Brand Identity & Design Tokens
// Re-exports from the centralized Bauhaus design token system.
// This file exists for backward compatibility — all values now
// come from bauhaus.ts.

export {
  FONT_FAMILY,
  HEADING_FONT_FAMILY,
  NEXIS_PRIMARY,
  NEXIS_PRIMARY_HOVER,
  NEXIS_PRIMARY_LIGHT,
  NEXIS_PRIMARY_GLOW,
  NEXIS_DARK_BG,
  NEXIS_DARK_CARD,
  NEXIS_DARK_ELEVATED,
  NEXIS_DARK_BORDER,
  NEXIS_DARK_TEXT,
  NEXIS_DARK_MUTED,
  NEXIS_LIGHT_BG,
  NEXIS_LIGHT_CARD,
  NEXIS_LIGHT_BORDER,
  NEXIS_LIGHT_TEXT,
  NEXIS_LIGHT_MUTED,
  ACCENT_CORAL,
  ACCENT_AMBER,
  ACCENT_MINT,
  ACCENT_CYAN,
  ACCENT_PURPLE,
  AGENT_PALETTE,
  USER_COLOR,
  USER_COLOR_LIGHT,
  USER_COLOR_SOFT,
  USER_COLOR_MEDIUM,
  GOV_NAVY,
  GOV_BLUE,
  GOV_SURFACE,
  GOV_BORDER,
} from './bauhaus';
